In [137]:
import pandas as pd
df=pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [138]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head() #these parameters are not necessary.

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [139]:
target = df.Survived
inputs= df.drop('Survived',axis='columns')

In [140]:
dummies = pd.get_dummies(inputs.Sex,dtype=int)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [141]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [142]:
inputs= inputs.drop('Sex',axis='columns')
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [143]:
inputs.columns[inputs.isnull().any()]

#This line finds if there are any NaN or null values in the inputs dataframe

Index(['Age'], dtype='object')

In [144]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [145]:
x = inputs.Age.mean()
inputs.Age=inputs.Age.fillna(x)

#fills the NaN with the average Age value

In [146]:
inputs.head(7)

   Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1
6       1  54.000000  51.8625       0     1

In [147]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [148]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [149]:
model.fit(X_train,y_train)

GaussianNB()

In [150]:
model.score(X_test,y_test)

0.776536312849162

In [151]:
model.predict(X_test)

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0], dtype=int64)

In [152]:
model.predict_proba(X_test[:10])

array([[0.98788727, 0.01211273],
       [0.0551499 , 0.9448501 ],
       [0.9887344 , 0.0112656 ],
       [0.04214231, 0.95785769],
       [0.98780816, 0.01219184],
       [0.98984665, 0.01015335],
       [0.98948134, 0.01051866],
       [0.97131338, 0.02868662],
       [0.98996264, 0.01003736],
       [0.02946487, 0.97053513]])

In [153]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.79020979, 0.75524476, 0.78169014, 0.81690141, 0.78169014])